
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;
//import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import java.sql.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author rfigu
 */
public class FormLista extends javax.swing.JInternalFrame {
    Connection conex;
    Statement st;
    //JList<String> jList1;
    //Producto cl=new Producto();
    Venta venta=new Venta();
    //Detalle detalle=new Detalle();
    private DefaultListModel listModel;
    private ArrayList<String> datos=new ArrayList<>();
    DefaultTableModel modelo = new DefaultTableModel();
    int i=0;
    //double tpagar=0.0;
    /**
     * Creates new form Ejemplo
     */
    public FormLista() {
        conectar();
        //Principall();
        initComponents();
        //llenaCombo();
        //listar();
        //listado();
        calcularTotal();
        //listadoDetalle();
        //agregarMouseListenerATabla();
    }
    public void conectar(){
      String url="jdbc:mysql://localhost:3306/metalshop";
      String usuario="root";
      String pass="";
      try{
          conex=DriverManager.getConnection(url,usuario,pass);
          //JOptionPane.showMessageDialog(null,"conectado","conection",1);
      }catch(Exception ex){
          System.out.println("ERROR EN CONEXION");
      }   
    }
    
    public void listado(JTable jtbVenta, String cadena) {
        List<Venta> lista = new ArrayList<>();
        try {
            st = conex.createStatement();
            ResultSet rs = st.executeQuery("SELECT * from venta where CONCAT (id_venta, cliente_venta, vendedor_venta, numero_venta, fecha_venta, monto_venta,estado_venta) LIKE '%"+cadena+"%'");
            while (rs.next()) {
                Venta venta = new Venta(rs.getInt("id_venta"), rs.getInt("cliente_venta"), rs.getInt("vendedor_venta"), rs.getString("numero_venta"), rs.getString("fecha_venta"), rs.getDouble("monto_venta"),rs.getString("estado_venta"));
                
                lista.add(venta);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en SELECT: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }

        modelo = (DefaultTableModel) jtbVenta.getModel();
        modelo.setRowCount(0);
        Object[] ob = new Object[7];
        for (Venta venta : lista) {
            ob[0] = venta.getId();
            ob[1] = venta.getId_Cliente();
            ob[2] = venta.getId_Vendedor();
            ob[3] = venta.getNum();
            ob[4] = venta.getFecha();  
            ob[5] = venta.getMonto();           
            ob[6] = venta.getEstado();
            modelo.addRow(ob);
        }
        jtbVenta.setModel(modelo);
        calcularTotal();
    }
    
   
    
    void calcularTotal(){
      double tpagar=0.0;  
      for (int i=0;i<jtbVenta.getRowCount();i++){         
          double value = Double.parseDouble(jtbVenta.getValueAt(i, 5).toString());
          tpagar += value;
          
      }            
          txtTotalVentas.setText(String.format("%.2f", tpagar));
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCliente = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbVenta = new javax.swing.JTable();
        txtTotalVentas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnCargarListado = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        lblListado = new javax.swing.JLabel();
        btnSalirVenta = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setTitle("LISTADO DE VENTAS METALSHOP");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtbVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID VENTA", "ID CLIENTE", "ID VENDEDOR", "NUM VENTA", "FECHA VENTA", "MONTO VENTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbVenta);

        txtTotalVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("TOTALES :");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnCargarListado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCargarListado.setText("CARGAR LISTADO");
        btnCargarListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarListadoActionPerformed(evt);
            }
        });

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFecha.setText("Ingrese Fecha :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTotalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lblFecha)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnCargarListado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarListado)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19))
        );

        lblListado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblListado.setText("Listado de Venta");

        btnSalirVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalirVenta.setText("VOLVER");
        btnSalirVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalirVenta)
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(lblListado, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSalirVenta)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirVentaActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_btnSalirVentaActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        
        listado(jtbVenta, txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnCargarListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarListadoActionPerformed
        
        listado(jtbVenta, "");
        txtBuscar.setText(null);
    }//GEN-LAST:event_btnCargarListadoActionPerformed
  
  
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCliente;
    private javax.swing.JButton btnCargarListado;
    private javax.swing.JButton btnSalirVenta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jtbVenta;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblListado;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtTotalVentas;
    // End of variables declaration//GEN-END:variables
}
