/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;
import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import javax.swing.JDesktopPane;
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.Statement;

import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import java.awt.*;
import java.sql.*;



/**
 *
 * @author rfigu
 */

public class Principal extends javax.swing.JFrame {
    Connection conex;
    Statement st;
    //private JList<String> jList1;
    //private DefaultListModel<String> listModel;
    ArrayList<String> datos=new ArrayList<>();
    int i=0;
    //private javax.swing.JDesktopPane VentanaP;
    //private JDesktopPane VentanaP;
    /**
     * Creates new form Ejemplo
     */
    //private javax.swing.JDesktopPane VentanaP;
    public Principal() {
        conectar();
        //Principall();
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        //llenaCombo();
    }
    public void conectar(){
      String url="jdbc:mysql://localhost:3306/metalshop";
      String usuario="root";
      String pass="";
      try{
          conex=DriverManager.getConnection(url,usuario,pass);
          JOptionPane.showMessageDialog(null,"conectado","conection",1);
      }catch(Exception ex){
          System.out.println("ERROR EN CONEXION");
      }   
    }


//public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    //public void Principall() {
     //   initComponents();
       // this.setExtendedState(MAXIMIZED_BOTH);
   // }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        Ventas = new javax.swing.JMenu();
        GenerarVenta = new javax.swing.JMenuItem();
        Mantenimiento = new javax.swing.JMenu();
        Cliente = new javax.swing.JMenuItem();
        Producto = new javax.swing.JMenuItem();
        Vendedor = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        ReportesVentas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("METALSHOP");
        setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));

        VentanaP.setBackground(new java.awt.Color(204, 204, 204));
        VentanaP.setMaximumSize(new java.awt.Dimension(606, 483));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout VentanaPLayout = new javax.swing.GroupLayout(VentanaP);
        VentanaP.setLayout(VentanaPLayout);
        VentanaPLayout.setHorizontalGroup(
            VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        VentanaPLayout.setVerticalGroup(
            VentanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuBar.setBackground(new java.awt.Color(0, 0, 0));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio.jpeg"))); // NOI18N
        Menu.setText("Menu");
        Menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Menu.add(Salir);

        menuBar.add(Menu);

        Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrocompra.png"))); // NOI18N
        Ventas.setText("Ventas");
        Ventas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasActionPerformed(evt);
            }
        });

        GenerarVenta.setText("Generar");
        GenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarVentaActionPerformed(evt);
            }
        });
        Ventas.add(GenerarVenta);

        menuBar.add(Ventas);

        Mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/manteni.png"))); // NOI18N
        Mantenimiento.setText("Mantenimiento");
        Mantenimiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        Cliente.setText("Cliente");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        Mantenimiento.add(Cliente);

        Producto.setText("Producto");
        Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoActionPerformed(evt);
            }
        });
        Mantenimiento.add(Producto);

        Vendedor.setText("Vendedor");
        Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendedorActionPerformed(evt);
            }
        });
        Mantenimiento.add(Vendedor);

        menuBar.add(Mantenimiento);

        Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        Reportes.setText("Reportes");
        Reportes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesActionPerformed(evt);
            }
        });

        ReportesVentas.setText("Reportes de Ventas");
        ReportesVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesVentasActionPerformed(evt);
            }
        });
        Reportes.add(ReportesVentas);

        menuBar.add(Reportes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        
    }//GEN-LAST:event_MenuActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
         System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasActionPerformed
     
    }//GEN-LAST:event_VentasActionPerformed

    private void GenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarVentaActionPerformed
       
        FormVenta v=new FormVenta();
        CentrarVentana(v);
       
    }//GEN-LAST:event_GenerarVentaActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        FormCliente v=new FormCliente();
        CentrarVentana(v);
    }//GEN-LAST:event_ClienteActionPerformed

    private void ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoActionPerformed
        FormProducto v=new FormProducto();
        CentrarVentana(v);
    }//GEN-LAST:event_ProductoActionPerformed

    private void VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendedorActionPerformed
        FormVendedor v=new FormVendedor();
        CentrarVentana(v);
    }//GEN-LAST:event_VendedorActionPerformed

    private void ReportesVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesVentasActionPerformed
        FormLista v=new FormLista();
        CentrarVentana(v);
    }//GEN-LAST:event_ReportesVentasActionPerformed

    private void ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportesActionPerformed
           
        void CentrarVentana(JInternalFrame frame){
        
            
        VentanaP.add(frame);  
        Dimension dimensionVentanaP = VentanaP.getSize();
        Dimension dimensionFrame = frame.getSize();
        
        int x = (dimensionVentanaP.width - dimensionFrame.width) / 2;
        int y = (dimensionVentanaP.height - dimensionFrame.height) / 2;
        
        frame.setLocation(x, y);
        frame.show();
        
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cliente;
    private javax.swing.JMenuItem GenerarVenta;
    private javax.swing.JMenu Mantenimiento;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem Producto;
    private javax.swing.JMenu Reportes;
    private javax.swing.JMenuItem ReportesVentas;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem Vendedor;
    public static javax.swing.JPanel VentanaP;
    private javax.swing.JMenu Ventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
